#
# TABLE STRUCTURE FOR: products
#

DROP TABLE IF EXISTS `products`;

CREATE TABLE `products` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `vendor_id` int(11) NOT NULL,
  `name` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `qty` int(11) NOT NULL,
  `description` varchar(2000) COLLATE utf8_unicode_ci DEFAULT NULL,
  `price` decimal(4,2) NOT NULL,
  `unit_measure` varchar(5) COLLATE utf8_unicode_ci DEFAULT NULL,
  `storage_id` int(11) NOT NULL,
  `categorie_id` int(11) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `fk_products_vendors` (`vendor_id`),
  KEY `fk_products_storage` (`storage_id`),
  KEY `fk_products_categories` (`categorie_id`),
  KEY `idx_products_name` (`name`),
  KEY `idx_products_price` (`price`),
  KEY `idx_products_unit_measure` (`unit_measure`),
  CONSTRAINT `fk_products_categories` FOREIGN KEY (`categorie_id`) REFERENCES `categories` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `fk_products_storage` FOREIGN KEY (`storage_id`) REFERENCES `storage` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `fk_products_vendors` FOREIGN KEY (`vendor_id`) REFERENCES `vendors` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=76 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `products` (`id`, `vendor_id`, `name`, `qty`, `description`, `price`, `unit_measure`, `storage_id`, `categorie_id`, `created_at`) VALUES (26, 12, 'necessitatibus', 0, 'Accusantium hic mollitia animi beatae magni ea. Est aut non et. Voluptatem et mollitia et. Iure sed odit veritatis laboriosam consectetur autem.', '46.19', 'dolor', 3, 8, '1970-07-18 10:47:27');
INSERT INTO `products` (`id`, `vendor_id`, `name`, `qty`, `description`, `price`, `unit_measure`, `storage_id`, `categorie_id`, `created_at`) VALUES (27, 13, 'fugiat', 3397570, 'Consequatur officiis recusandae totam quo aut. Totam quae quae sunt officiis magni doloremque. Neque nam alias esse voluptas iste. Ratione rerum dignissimos veritatis.', '99.99', 'volup', 4, 9, '2008-11-21 09:49:50');
INSERT INTO `products` (`id`, `vendor_id`, `name`, `qty`, `description`, `price`, `unit_measure`, `storage_id`, `categorie_id`, `created_at`) VALUES (28, 14, 'corporis', 208, 'Qui repudiandae illum veniam eius. Non et perferendis repellat quo. Soluta cum et quibusdam doloribus iure. Cumque labore vel quae et qui libero. Quo rerum quia perferendis libero nisi distinctio.', '99.99', 'commo', 5, 10, '1985-04-22 19:27:45');
INSERT INTO `products` (`id`, `vendor_id`, `name`, `qty`, `description`, `price`, `unit_measure`, `storage_id`, `categorie_id`, `created_at`) VALUES (29, 15, 'dolor', 89, 'Est cum similique impedit ea vitae pariatur dolore. Porro non sunt sit iure. Non vero doloribus dignissimos sunt est nesciunt.', '1.97', 'maxim', 6, 8, '2019-08-13 19:46:56');
INSERT INTO `products` (`id`, `vendor_id`, `name`, `qty`, `description`, `price`, `unit_measure`, `storage_id`, `categorie_id`, `created_at`) VALUES (30, 16, 'commodi', 9920834, 'Animi sint nulla quod illum architecto veniam voluptas. Ut id possimus quia. Similique dolores nihil voluptatem est debitis et. Omnis quia dolorem vel accusantium sint.', '99.99', 'et', 3, 9, '1971-10-03 22:49:20');
INSERT INTO `products` (`id`, `vendor_id`, `name`, `qty`, `description`, `price`, `unit_measure`, `storage_id`, `categorie_id`, `created_at`) VALUES (31, 17, 'ut', 1171652, 'Omnis culpa aut occaecati accusamus. Sit ut enim eligendi. Recusandae quo recusandae consequuntur voluptatibus id eos sapiente.', '0.00', 'dolor', 4, 10, '1986-08-11 10:28:02');
INSERT INTO `products` (`id`, `vendor_id`, `name`, `qty`, `description`, `price`, `unit_measure`, `storage_id`, `categorie_id`, `created_at`) VALUES (32, 18, 'temporibus', 387904768, 'Omnis quis maxime qui eos omnis illum. Est dolorem officiis eaque exercitationem omnis non quae. Blanditiis ab debitis vitae delectus animi qui rem eveniet.', '99.99', 'rerum', 5, 8, '2007-04-09 18:35:02');
INSERT INTO `products` (`id`, `vendor_id`, `name`, `qty`, `description`, `price`, `unit_measure`, `storage_id`, `categorie_id`, `created_at`) VALUES (33, 19, 'minus', 9, 'Placeat possimus autem ipsam enim velit minus velit deleniti. Et vel voluptatem nobis rerum. Aut enim blanditiis tempora aperiam non reprehenderit voluptatem.', '99.99', 'quod', 6, 9, '1990-12-21 17:16:38');
INSERT INTO `products` (`id`, `vendor_id`, `name`, `qty`, `description`, `price`, `unit_measure`, `storage_id`, `categorie_id`, `created_at`) VALUES (34, 20, 'et', 814910, 'Perferendis sit aspernatur pariatur omnis. Consequuntur dolore sint nihil odit tempore tenetur. Exercitationem sed et est reprehenderit aut necessitatibus neque. Et dolorem aperiam quia.', '0.00', 'porro', 3, 10, '1981-05-20 08:20:30');
INSERT INTO `products` (`id`, `vendor_id`, `name`, `qty`, `description`, `price`, `unit_measure`, `storage_id`, `categorie_id`, `created_at`) VALUES (35, 21, 'qui', 434, 'Nemo sint aut et quo. Temporibus maxime aliquid totam et optio voluptate aspernatur dolores.', '1.30', 'excep', 4, 8, '2012-02-13 13:31:28');
INSERT INTO `products` (`id`, `vendor_id`, `name`, `qty`, `description`, `price`, `unit_measure`, `storage_id`, `categorie_id`, `created_at`) VALUES (36, 12, 'dolore', 374, 'Unde et quisquam blanditiis. Cumque quis harum aut cum ut commodi et. Placeat adipisci eligendi necessitatibus consequatur dicta qui sunt. Sint dignissimos voluptatem et consequatur aut laboriosam quam.', '0.00', 'volup', 5, 9, '1988-05-22 08:30:27');
INSERT INTO `products` (`id`, `vendor_id`, `name`, `qty`, `description`, `price`, `unit_measure`, `storage_id`, `categorie_id`, `created_at`) VALUES (37, 13, 'ut', 968218, 'Vel debitis nemo et magni omnis est. Vel ratione in ut laborum. Voluptatem soluta vel commodi nulla perspiciatis. Et occaecati officiis ut cupiditate excepturi recusandae.', '99.99', 'eveni', 6, 10, '1991-02-28 12:35:05');
INSERT INTO `products` (`id`, `vendor_id`, `name`, `qty`, `description`, `price`, `unit_measure`, `storage_id`, `categorie_id`, `created_at`) VALUES (38, 14, 'corporis', 8, 'Blanditiis officiis nesciunt in illo cupiditate ut vero. Earum aut nobis non. Cum ab nesciunt corporis est. Odio quam minima ut et numquam. Deleniti vel non velit quo aut.', '99.99', 'incid', 3, 8, '1998-05-25 12:06:42');
INSERT INTO `products` (`id`, `vendor_id`, `name`, `qty`, `description`, `price`, `unit_measure`, `storage_id`, `categorie_id`, `created_at`) VALUES (39, 15, 'occaecati', 6395, 'Nobis ea optio possimus quia ipsam qui molestias voluptate. Est sint et cupiditate ad minima architecto mollitia. Voluptatem et ea nulla eos modi est.', '99.99', 'porro', 4, 9, '2008-12-15 11:51:06');
INSERT INTO `products` (`id`, `vendor_id`, `name`, `qty`, `description`, `price`, `unit_measure`, `storage_id`, `categorie_id`, `created_at`) VALUES (40, 16, 'harum', 86795934, 'Pariatur sequi reiciendis voluptates voluptatem sed. Rem nihil aliquam non aut id. Quaerat non optio voluptatem id doloremque. In rerum ea nisi similique dolor est rerum.', '77.60', 'bland', 5, 10, '1993-05-19 07:52:48');
INSERT INTO `products` (`id`, `vendor_id`, `name`, `qty`, `description`, `price`, `unit_measure`, `storage_id`, `categorie_id`, `created_at`) VALUES (41, 17, 'sit', 636314805, 'Expedita laudantium quae consequatur modi repellat labore dolores quia. Asperiores veritatis consequatur odio. Pariatur aut quae autem animi esse et praesentium. Facilis occaecati commodi voluptas expedita.', '99.99', 'saepe', 6, 8, '1985-01-21 23:40:29');
INSERT INTO `products` (`id`, `vendor_id`, `name`, `qty`, `description`, `price`, `unit_measure`, `storage_id`, `categorie_id`, `created_at`) VALUES (42, 18, 'omnis', 619263867, 'Qui id optio cupiditate nobis. Ducimus quia et et. Quo magni adipisci sit iusto enim ut recusandae. Quia cum deleniti repellendus qui.', '99.99', 'volup', 3, 9, '1990-01-22 15:25:23');
INSERT INTO `products` (`id`, `vendor_id`, `name`, `qty`, `description`, `price`, `unit_measure`, `storage_id`, `categorie_id`, `created_at`) VALUES (43, 19, 'cupiditate', 2635997, 'Sit tempora dolores aut accusantium deleniti. Nihil ea tempora id. Autem perferendis ut aut qui maxime deserunt hic fugiat.', '99.99', 'offic', 4, 10, '1997-08-13 22:52:22');
INSERT INTO `products` (`id`, `vendor_id`, `name`, `qty`, `description`, `price`, `unit_measure`, `storage_id`, `categorie_id`, `created_at`) VALUES (44, 20, 'cumque', 9, 'Quisquam ut repellendus qui sunt nostrum vero eligendi. Qui nam harum quaerat quisquam eos recusandae ut sed. Officia sapiente quo iure rerum cum.', '99.99', 'labor', 5, 8, '1992-04-04 15:10:50');
INSERT INTO `products` (`id`, `vendor_id`, `name`, `qty`, `description`, `price`, `unit_measure`, `storage_id`, `categorie_id`, `created_at`) VALUES (45, 21, 'saepe', 580, 'Ratione quisquam quo nihil ut dolore sed aliquam. Esse repudiandae officia dolorum. Nostrum dolorum alias ducimus vel rem quia consectetur quasi.', '42.53', 'et', 6, 9, '2019-08-08 03:45:50');
INSERT INTO `products` (`id`, `vendor_id`, `name`, `qty`, `description`, `price`, `unit_measure`, `storage_id`, `categorie_id`, `created_at`) VALUES (46, 12, 'est', 7412, 'Odio autem sapiente iste. Pariatur maxime sed aut voluptas enim est minus. Magnam facilis et sint nobis accusamus qui. Consequatur consequatur sit repudiandae vel occaecati.', '99.99', 'vitae', 3, 10, '2000-02-11 20:00:21');
INSERT INTO `products` (`id`, `vendor_id`, `name`, `qty`, `description`, `price`, `unit_measure`, `storage_id`, `categorie_id`, `created_at`) VALUES (47, 13, 'incidunt', 8617045, 'Officia ipsa vitae fugit eum sint reprehenderit repellendus. Nulla est placeat quam. Qui maxime temporibus debitis quis sunt.', '99.99', 'eum', 4, 8, '2015-11-12 04:45:22');
INSERT INTO `products` (`id`, `vendor_id`, `name`, `qty`, `description`, `price`, `unit_measure`, `storage_id`, `categorie_id`, `created_at`) VALUES (48, 14, 'quam', 7744, 'Ab atque accusamus maxime. Cum est et qui cum incidunt. Aut vitae sed saepe eos eos quia.', '99.99', 'cupid', 5, 9, '2016-12-12 04:04:33');
INSERT INTO `products` (`id`, `vendor_id`, `name`, `qty`, `description`, `price`, `unit_measure`, `storage_id`, `categorie_id`, `created_at`) VALUES (49, 15, 'hic', 0, 'Consectetur at beatae ea voluptas iste at. Error numquam ut animi voluptas voluptatem. Dolor et praesentium corrupti autem modi eos. Exercitationem quae est optio ex illo necessitatibus velit. Ipsum earum qui impedit.', '0.00', 'omnis', 6, 10, '2004-03-31 10:54:19');
INSERT INTO `products` (`id`, `vendor_id`, `name`, `qty`, `description`, `price`, `unit_measure`, `storage_id`, `categorie_id`, `created_at`) VALUES (50, 16, 'vero', 9837, 'Autem minus dolore ut voluptatem unde molestiae sit. Vero dolor harum enim modi quia maiores voluptates est. Voluptatem harum aspernatur perspiciatis magni ipsum aut. Perspiciatis sint delectus rerum consequatur voluptates omnis.', '99.99', 'sed', 3, 8, '1988-02-06 10:55:53');
INSERT INTO `products` (`id`, `vendor_id`, `name`, `qty`, `description`, `price`, `unit_measure`, `storage_id`, `categorie_id`, `created_at`) VALUES (51, 17, 'et', 77876470, 'Ipsa qui dolores vero atque a. Minus possimus est ea accusamus qui qui. Qui voluptatum minima molestiae maxime magni rerum dolorem. Eum quia dolores impedit quo corrupti repellat.', '8.25', 'nam', 4, 9, '1985-02-17 00:59:54');
INSERT INTO `products` (`id`, `vendor_id`, `name`, `qty`, `description`, `price`, `unit_measure`, `storage_id`, `categorie_id`, `created_at`) VALUES (52, 18, 'doloremque', 65280591, 'Soluta sint culpa est minus reprehenderit aliquam. Dolorem fugit provident consectetur earum. Dolore aut explicabo repudiandae et dignissimos dolore. Laborum velit suscipit voluptas.', '99.99', 'magna', 5, 10, '1983-01-05 13:26:26');
INSERT INTO `products` (`id`, `vendor_id`, `name`, `qty`, `description`, `price`, `unit_measure`, `storage_id`, `categorie_id`, `created_at`) VALUES (53, 19, 'illo', 4195, 'Vitae debitis ab non enim sit voluptas provident. Perspiciatis molestiae inventore facilis officiis molestias. Nobis autem quia quo velit ratione. Minima quisquam quo occaecati.', '1.40', 'quia', 6, 8, '2014-01-21 17:17:29');
INSERT INTO `products` (`id`, `vendor_id`, `name`, `qty`, `description`, `price`, `unit_measure`, `storage_id`, `categorie_id`, `created_at`) VALUES (54, 20, 'praesentium', 2370, 'Est blanditiis recusandae nobis ut illo amet. Quis fuga et fugit vel. Est quisquam delectus libero. Cum vitae itaque provident temporibus autem in. Dolorum tempore et est blanditiis sint culpa non.', '99.99', 'moles', 3, 9, '1980-01-18 23:21:04');
INSERT INTO `products` (`id`, `vendor_id`, `name`, `qty`, `description`, `price`, `unit_measure`, `storage_id`, `categorie_id`, `created_at`) VALUES (55, 21, 'ratione', 833, 'Rerum impedit dolor molestiae et aspernatur aut. Incidunt quidem blanditiis non architecto sunt eligendi ipsum. Facere possimus deleniti est. Et sequi commodi ipsam quibusdam eligendi nihil.', '99.99', 'accus', 4, 10, '1996-05-14 06:03:25');
INSERT INTO `products` (`id`, `vendor_id`, `name`, `qty`, `description`, `price`, `unit_measure`, `storage_id`, `categorie_id`, `created_at`) VALUES (56, 12, 'in', 3, 'Dolorem dicta odit nobis minima porro fugit. Quae id est et et facere porro. Nemo et nulla autem doloremque exercitationem. A facere error libero beatae.', '99.99', 'aut', 5, 8, '1999-09-08 05:50:15');
INSERT INTO `products` (`id`, `vendor_id`, `name`, `qty`, `description`, `price`, `unit_measure`, `storage_id`, `categorie_id`, `created_at`) VALUES (57, 13, 'dolor', 3805, 'Ut beatae nihil et officia iusto natus. Velit et harum modi eos ab nihil laudantium.', '99.99', 'place', 6, 9, '2003-08-05 20:48:01');
INSERT INTO `products` (`id`, `vendor_id`, `name`, `qty`, `description`, `price`, `unit_measure`, `storage_id`, `categorie_id`, `created_at`) VALUES (58, 14, 'et', 5435112, 'Earum dolores ex aliquid in placeat nemo molestiae voluptas. Harum sit sint quae consequatur exercitationem. Sed accusantium dolorem voluptatem et rerum.', '99.99', 'corpo', 3, 10, '1986-04-10 01:28:41');
INSERT INTO `products` (`id`, `vendor_id`, `name`, `qty`, `description`, `price`, `unit_measure`, `storage_id`, `categorie_id`, `created_at`) VALUES (59, 15, 'doloremque', 95, 'Fuga voluptatem assumenda pariatur ullam consequatur veritatis fugiat. Quos aut beatae provident ipsum. Perferendis ea qui a quis mollitia. Eum aut reprehenderit quam fuga.', '99.99', 'simil', 4, 8, '1973-10-07 13:55:05');
INSERT INTO `products` (`id`, `vendor_id`, `name`, `qty`, `description`, `price`, `unit_measure`, `storage_id`, `categorie_id`, `created_at`) VALUES (60, 16, 'sed', 0, 'Nobis aliquid et saepe voluptatem sed ut nesciunt. Maxime non doloribus rerum magnam. Nemo qui quisquam dolorem velit et vitae.', '0.00', 'et', 5, 9, '2016-04-14 01:13:43');
INSERT INTO `products` (`id`, `vendor_id`, `name`, `qty`, `description`, `price`, `unit_measure`, `storage_id`, `categorie_id`, `created_at`) VALUES (61, 17, 'autem', 98410575, 'Temporibus occaecati impedit architecto deleniti iure ut nihil omnis. Labore eos rerum officiis. Ut asperiores quas minus neque voluptates corrupti.', '71.23', 'velit', 6, 10, '1991-11-01 11:33:44');
INSERT INTO `products` (`id`, `vendor_id`, `name`, `qty`, `description`, `price`, `unit_measure`, `storage_id`, `categorie_id`, `created_at`) VALUES (62, 18, 'ullam', 0, 'Earum cupiditate recusandae porro commodi maxime quam quas. Non animi quas doloribus omnis fugit aut voluptatem. Deserunt qui voluptatem harum enim nesciunt cum aut. Facere harum amet et voluptates dignissimos odio quae corporis.', '0.00', 'id', 3, 8, '2020-07-11 09:04:22');
INSERT INTO `products` (`id`, `vendor_id`, `name`, `qty`, `description`, `price`, `unit_measure`, `storage_id`, `categorie_id`, `created_at`) VALUES (63, 19, 'molestiae', 75, 'Et debitis ducimus eum itaque voluptatem. Ullam aut quo nisi molestiae quas saepe sed aut. Maxime reiciendis ducimus temporibus sint. Quis culpa adipisci sit magni temporibus maxime ut nihil.', '51.97', 'aperi', 4, 9, '2006-07-21 10:30:38');
INSERT INTO `products` (`id`, `vendor_id`, `name`, `qty`, `description`, `price`, `unit_measure`, `storage_id`, `categorie_id`, `created_at`) VALUES (64, 20, 'architecto', 85, 'Voluptatem voluptate et voluptatem ipsa dicta ut. Laudantium at eveniet impedit numquam aut. Quia dignissimos ut facere dolorem. Qui cumque hic nihil repudiandae et tempore.', '99.99', 'velit', 5, 10, '2015-02-09 11:43:48');
INSERT INTO `products` (`id`, `vendor_id`, `name`, `qty`, `description`, `price`, `unit_measure`, `storage_id`, `categorie_id`, `created_at`) VALUES (65, 21, 'eos', 34536129, 'Vel quo est ut modi. Consequuntur qui assumenda asperiores. Cupiditate sed qui voluptas temporibus aperiam numquam.', '99.99', 'repud', 6, 8, '2002-07-08 11:29:12');
INSERT INTO `products` (`id`, `vendor_id`, `name`, `qty`, `description`, `price`, `unit_measure`, `storage_id`, `categorie_id`, `created_at`) VALUES (66, 12, 'rem', 972062, 'Doloremque delectus laudantium error deleniti ipsam eius. Totam doloremque rerum at commodi minima nobis asperiores. Sed accusamus ea provident.', '8.74', 'assum', 3, 9, '2005-06-25 07:08:18');
INSERT INTO `products` (`id`, `vendor_id`, `name`, `qty`, `description`, `price`, `unit_measure`, `storage_id`, `categorie_id`, `created_at`) VALUES (67, 13, 'eos', 5, 'Nihil sint praesentium vero autem. Et facilis rerum nihil sit enim totam. Laboriosam aliquam repellendus repellat quia numquam non. A eum ea ut eum.', '99.99', 'volup', 4, 10, '2010-05-15 00:11:07');
INSERT INTO `products` (`id`, `vendor_id`, `name`, `qty`, `description`, `price`, `unit_measure`, `storage_id`, `categorie_id`, `created_at`) VALUES (68, 14, 'voluptates', 2402, 'Eum asperiores sint porro et officia ut. Atque quia porro fugit aut hic.', '99.99', 'eaque', 5, 8, '2009-06-11 05:58:24');
INSERT INTO `products` (`id`, `vendor_id`, `name`, `qty`, `description`, `price`, `unit_measure`, `storage_id`, `categorie_id`, `created_at`) VALUES (69, 15, 'accusamus', 180878, 'Nihil occaecati tempore sint repellendus reiciendis non quisquam. Eaque quas non deleniti libero omnis molestiae ullam. Facilis eaque impedit et. Ducimus earum cum accusamus totam eveniet ipsam.', '99.99', 'minus', 6, 9, '2008-06-26 11:34:33');
INSERT INTO `products` (`id`, `vendor_id`, `name`, `qty`, `description`, `price`, `unit_measure`, `storage_id`, `categorie_id`, `created_at`) VALUES (70, 16, 'blanditiis', 762, 'Qui consequatur asperiores est qui. Et nesciunt eos laudantium itaque omnis iusto. Impedit facere perferendis atque ipsa nostrum.', '99.99', 'tenet', 3, 10, '2004-12-02 06:09:48');
INSERT INTO `products` (`id`, `vendor_id`, `name`, `qty`, `description`, `price`, `unit_measure`, `storage_id`, `categorie_id`, `created_at`) VALUES (71, 17, 'alias', 5593, 'Voluptas deleniti quia sed alias voluptatibus. Eum neque et sit dolor totam velit. Molestiae et a facilis voluptates officiis.', '0.00', 'et', 4, 8, '2010-05-23 06:39:42');
INSERT INTO `products` (`id`, `vendor_id`, `name`, `qty`, `description`, `price`, `unit_measure`, `storage_id`, `categorie_id`, `created_at`) VALUES (72, 18, 'eum', 3542, 'Iusto at autem sequi. Iste maxime omnis veritatis quo molestias aut adipisci. Esse impedit sapiente aut harum doloribus ratione. Consequatur est recusandae temporibus omnis.', '0.00', 'corru', 5, 9, '1981-06-24 16:15:20');
INSERT INTO `products` (`id`, `vendor_id`, `name`, `qty`, `description`, `price`, `unit_measure`, `storage_id`, `categorie_id`, `created_at`) VALUES (73, 19, 'aliquam', 33175, 'Sint possimus beatae rem tempora non at. Ipsum voluptatem non sit dolore quia totam labore. Expedita aperiam id velit quia praesentium sit nobis.', '99.99', 'dolor', 6, 10, '2017-12-25 19:29:56');
INSERT INTO `products` (`id`, `vendor_id`, `name`, `qty`, `description`, `price`, `unit_measure`, `storage_id`, `categorie_id`, `created_at`) VALUES (74, 20, 'ipsum', 546443439, 'Veritatis ut corrupti officiis sunt ut placeat. Veritatis iusto molestias nesciunt qui. Nam rerum sint debitis animi praesentium.', '99.99', 'corru', 3, 8, '2001-06-04 00:15:19');
INSERT INTO `products` (`id`, `vendor_id`, `name`, `qty`, `description`, `price`, `unit_measure`, `storage_id`, `categorie_id`, `created_at`) VALUES (75, 21, 'impedit', 712342355, 'Voluptatibus tempora ipsum et ut ut accusamus. Numquam sunt quia occaecati est. Soluta neque magnam repudiandae qui quia quo.', '99.99', 'qui', 4, 9, '1991-08-18 22:30:48');


